# yaml-language-server: $schema=./pkg/config/config.schema.json
version: "1"

# Standard router settings
listen_addr: "localhost:3002"
graphql_path: "/graphql"

# ConnectRPC configuration
connect_rpc:
  enabled: true
  server:
    listen_addr: "localhost:5026"
  storage:
    provider_id: "fs-protos"
  graphql_endpoint: "http://localhost:3002/graphql"
  operations_dir: "./../../openapi-demo/operations"

# Storage provider for proto files
storage_providers:
  file_system:
    - id: "fs-protos"
      path: "./../../openapi-demo/proto"
